# Generated by Django 3.0.5 on 2021-03-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0006_auto_20210326_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='bio',
            new_name='description',
        ),
    ]
