# Generated by Django 3.0.5 on 2021-03-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0010_auto_20210327_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='description',
            new_name='bio',
        ),
    ]
