# Generated by Django 3.0.5 on 2021-03-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0011_auto_20210327_1358'),
        ('yamdb', '0005_auto_20210326_1059'),
    ]

    operations = [
    ]
