# Generated by Django 3.0.5 on 2021-03-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0013_auto_20210327_1726'),
        ('yamdb', '0012_merge_20210327_1205'),
    ]

    operations = [
    ]
