# Generated by Django 3.0.5 on 2021-03-29 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0016_auto_20210329_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='yamdb.Title'),
        ),
    ]
